//AUTH/LOGOUT
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

//ALL ROLES
export const FETCH_COURSES = 'FETCH_COURSES';

//TEACHER
export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';

//STUDENT
export const GENERATE_TICKET = 'GENERATE_TICKET';

//ADMIN
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const CREATE_COURSE = 'CREATE_COURSE';
export const CONNECT_STUDENT_TO_COURSE = 'CONNECT_STUDENT_TO_COURSE';
export const DELETE_USER = 'DELETE_USER';
export const CHANGE_COURSES_DATA = 'CHANGE_COURSES_DATA';